version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: interviewdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: interviewapp
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/interviewdb
      DB_USER: postgres
      DB_PASSWORD: 5432
    ports:
      - "8080:8080"

volumes:
  postgres_data: