spring.application.name=interviewapp

#spring.h2.console.enabled=true

jwt.refresh.expiration=604800000

jwt.secret=your_super_secret_key_which_is_long_enough_123456
jwt.expiration=900000


#spring.datasource.url=jdbc:h2:mem:testdb
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


#spring.datasource.url=jdbc:postgresql://localhost:5432/interviewdb

#spring.datasource.url=jdbc:postgresql://postgres:5432/interviewdb
#spring.datasource.username=postgres
#spring.datasource.password=5432

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

SPRING_DATASOURCE_URL=jdbc:postgresql://postgres.railway.internal:5432/railway
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=vWkjhbqDjzcIGxHMnCwnwNoBBCJtXBai


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
